FROM python:3.11-slim

WORKDIR /backend
COPY . /backend

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

CMD ["poetry", "run", "python", "src/manage.py", "runserver", "0.0.0.0:8000"]

