FROM python:3.11-slim

WORKDIR /app
COPY . /app

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

CMD ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]
