FROM node:20-alpine

WORKDIR /app

# zainstaluj narzędzia potrzebne do kompilacji
RUN apk add --no-cache python3 make g++

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev"]
