services:
  backend:
    environment:
      SECRET_KEY: django-insecure-89v(%b77o0-e$)!a4&)j6-#+y4ncspo_c9h%vs-5i(bawhp8mo
    env_file:
    - ../api/src/.env
    build:
      context: ../api
      dockerfile: ../docker/backend/dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../api:/backend

  console:
    build:
      context: ../console
      dockerfile: ../docker/console/dockerfile.console
    volumes:
      - ../console:/console
    stdin_open: true
    tty: true

  web:
    build:
      context: ../web
      dockerfile: ../docker/web/dockerfile.web
    ports:
      - "5173:5173"
    volumes:
      - ../web/src:/app/src
      - ../web/vite.config.ts:/app/vite.config.ts
      - ../web/package.json:/app/package.json
      - ../web/tsconfig.json:/app/tsconfig.json
    stdin_open: true
    tty: true

  desktop:
    build:
      context: ../desktop
      dockerfile: ../docker/desktop/dockerfile.desktop
    volumes:
      - ../desktop:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=host.docker.internal:0.0
    network_mode: host
    stdin_open: true
    tty: true
    shm_size: 256m
    
