services:
  backend:
    build:
      context: ../api
      dockerfile: ../docker/backend/dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../api:/backend

  console:
    build:
      context: ../console
      dockerfile: ../docker/console/dockerfile.console
    volumes:
      - ../console:/console
    stdin_open: true
    tty: true

  web:
    build:
      context: ../web
      dockerfile: ../docker/web/dockerfile.web
    ports:
      - "5173:5173"
    volumes:
      - ../web:/app 
      - /app/node_modules
    stdin_open: true
    tty: true

  desktop:
    build:
      context: ../desktop
      dockerfile: ../docker/desktop/dockerfile.desktop
    volumes:
      - ../desktop:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    stdin_open: true
    tty: true
    
