FROM python:3.11-slim

WORKDIR /app

# Copy requirements.txt first so that the cache works
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

# Copy whole console version
COPY . /app

CMD ["python", "ToDo.py"]
