# dockerfile.backend

FROM python:3.11-slim

WORKDIR /api

COPY pyproject.toml poetry.lock* ./

RUN pip install --upgrade pip && pip install poetry

RUN poetry config virtualenvs.create false \
    && poetry install --no-root

COPY . .

WORKDIR /api/src

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
