name: Build with Docker Compose

on:
  push:
    branches:
      - main
      - git_CI/CD
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose services
        run: docker compose -f docker/docker-compose.yml build

      - name: Run Django tests
        run: docker compose -f docker/docker-compose.yml run backend python manage.py test
