name: Build with Docker Compose

on:
  push:
    branches:
      - main
      - git_CI/CD
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose services
        run: docker compose -f docker/docker-compose.yml build --progress=plain

      - name: Run Django tests
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET }},
          GITHUB_SECRET: ${{ secrets.GH_SECRET }},
          GITHUB_CLIENT: ${{ secrets.GH_CLIENT }},
          OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }},
          OUATH_CLIENT: ${{ secrets.OUATH_CLIENT_ID }},
        run: |
          docker compose -f docker/docker-compose.yml run --rm \
            -e SECRET_KEY=$SECRET_KEY \
            --workdir /backend/src backend python manage.py test

      - name: Run Web tests
        run: docker compose -f docker/docker-compose.yml run --rm web npm run test

      - name: Run Console tests
        run: docker compose -f docker/docker-compose.yml run --rm console python test.py
