name: Build with Docker Compose

on:
  push:
    branches:
      - main
      - git_CI/CD
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose services
        run: docker compose -f docker/docker-compose.yml build --progress=plain

      - name: Run Django tests
        run: |
          docker compose -f docker/docker-compose.yml run --rm \
            --env-file /dev/null \
            -e SECRET_KEY=django-insecure-89v(%b77o0-e$)!a4&)j6-#+y4ncspo_c9h%vs-5i(bawhp8mo \
            -e DEBUG=True \
            -e DATABASE_URL=sqlite:///db.sqlite3 \
            --workdir /backend/src backend python manage.py test
            - name: Run Web tests
              run: docker compose -f docker/docker-compose.yml run --rm web npm run test

      - name: Run Console tests
        run: docker compose -f docker/docker-compose.yml run --rm console python test.py
